name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup vale
        run: |
          mkdir -p .vale/styles/config/vocabularies/Bitpaper

          cat > .vale.ini << 'EOF'
          StylesPath = .vale/styles
          MinAlertLevel = warning
          Packages = write-good
          Vocab = Bitpaper
          SkippedScopes = script, style, pre, code, code-block

          [*]
          BasedOnStyles = Vale, write-good
          EOF

          cat > .vale/styles/config/vocabularies/Bitpaper/accept.txt << 'EOF'
          (?i)Bitpaper
          preprocessors
          breakpoint
          async
          (?i)urls
          screensharing
          (?i)Whitelabelling
          EOF

      - uses: errata-ai/vale-action@v2
        with:
          reporter: github-check
          fail_on_error: true
          files: index.html
